import type { ImportConfig } from "./types";

export const brokerTemplates: Record<string, ImportConfig> = {
  commsec: {
    mapping: {
      tradeDate: "Trade Date",
      instrumentCode: "Security",
      quantity: "Units",
      price: "Average Price ($)",
      transactionType: "Buy/ Sell",
      brokerage: "Brokerage (inc GST.)",
      marketCode: null,
      comments: "Confirmation Number",
    },
    dateFormat: "dd/mm/yyyy",
    decimalSeparator: ".",
    transactionTypeMap: { B: "BUY", S: "SELL" },
  },
  selfwealth: {
    mapping: {
      tradeDate: "Trade Date",
      instrumentCode: "Stock",
      quantity: "Quantity",
      price: "Price",
      transactionType: "Side",
      brokerage: "Brokerage (inc GST)",
      marketCode: "Market",
      comments: "Notes",
    },
    dateFormat: "dd/mm/yyyy",
    decimalSeparator: ".",
    transactionTypeMap: { Buy: "BUY", Sell: "SELL" },
  },
  stake: {
    mapping: {
      tradeDate: "Date",
      instrumentCode: "Symbol",
      quantity: "Shares",
      price: "Price Per Share",
      transactionType: "Action",
      brokerage: "Fees",
      currency: "Currency",
      marketCode: null,
    },
    dateFormat: "yyyy-mm-dd",
    decimalSeparator: ".",
    transactionTypeMap: {
      "Market Buy": "BUY",
      "Market Sell": "SELL",
      "Limit Buy": "BUY",
      "Limit Sell": "SELL",
      Dividend: "DIVIDEND",
    },
  },
  cmc_markets: {
    mapping: {
      tradeDate: "Date/Time",
      instrumentCode: "Product",
      quantity: "Quantity",
      price: "Price",
      transactionType: "Type",
      brokerage: "Commission",
      marketCode: "Exchange",
      comments: "Reference",
    },
    dateFormat: "dd/mm/yyyy",
    decimalSeparator: ".",
    transactionTypeMap: { Buy: "BUY", Sell: "SELL" },
  },
  cmc_invest: {
    mapping: {
      tradeDate: "Trade Date",
      instrumentCode: "AsxCode",
      quantity: "Quantity",
      price: "Price",
      transactionType: "Order Type",
      brokerage: "Brokerage",
      marketCode: null,
      comments: "Confirmation Number",
    },
    dateFormat: "yyyy-mm-dd",
    decimalSeparator: ".",
    transactionTypeMap: { Buy: "BUY", Sell: "SELL" },
  },
  bell_direct: {
    mapping: {
      tradeDate: "Date Completed",
      instrumentCode: "Stock Code",
      quantity: "Quantity",
      price: "Average Transacted Price",
      transactionType: "Buy/Sell",
      brokerage: "Brokerage",
      marketCode: null,
      comments: "Contract",
    },
    dateFormat: "dd mmm yyyy hh:mm",
    decimalSeparator: ".",
    transactionTypeMap: { Buy: "BUY", Sell: "SELL" },
  },
  nabtrade: {
    mapping: {
      tradeDate: "Trade Date",
      instrumentCode: "ASX Code",
      quantity: "Units",
      price: "Price",
      transactionType: "Buy/Sell",
      brokerage: "Brokerage ($)",
      marketCode: null,
      comments: "Description",
    },
    dateFormat: "dd/mm/yyyy",
    decimalSeparator: ".",
    transactionTypeMap: { Buy: "BUY", Sell: "SELL" },
  },
  fiig: {
    mapping: {
      tradeDate: "Settlement Date",
      instrumentCode: "ISIN",
      quantity: "Face Value",
      price: "Clean Price",
      transactionType: "Trade Type",
      brokerage: "Fee",
      marketCode: null,
      currency: "Currency",
      comments: "Issuer",
      couponRate: "Coupon",
      maturityDate: "Maturity",
      faceValue: "Face Value",
      paymentFrequency: "Frequency",
    },
    dateFormat: "dd/mm/yyyy",
    decimalSeparator: ".",
    transactionTypeMap: { Buy: "BUY", Sell: "SELL", Maturity: "MATURITY" },
  },
  interactive_brokers: {
    mapping: {
      tradeDate: "Date/Time",
      instrumentCode: "Symbol",
      quantity: "Quantity",
      price: "T. Price",
      transactionType: "Code",
      brokerage: "Comm/Fee",
      currency: "Currency",
      exchangeRate: "Forex",
      marketCode: "Exchange",
      comments: "Description",
    },
    dateFormat: "yyyy-mm-dd",
    decimalSeparator: ".",
    transactionTypeMap: {
      O: "BUY",
      C: "SELL",
      BOT: "BUY",
      SLD: "SELL",
    },
  },
};

export function getBrokerTemplate(broker: string): ImportConfig | null {
  return brokerTemplates[broker] || null;
}

export function listBrokerTemplates(): Array<{ id: string; name: string }> {
  return [
    { id: "commsec", name: "CommSec" },
    { id: "selfwealth", name: "SelfWealth" },
    { id: "stake", name: "Stake" },
    { id: "cmc_markets", name: "CMC Markets" },
    { id: "cmc_invest", name: "CMC Invest" },
    { id: "bell_direct", name: "Bell Direct" },
    { id: "nabtrade", name: "nabtrade" },
    { id: "fiig", name: "FIIG Securities" },
    { id: "interactive_brokers", name: "Interactive Brokers" },
  ];
}
